### ISSUE TITLE
libc++.1.dylib

### ISSUE THREAD

**Issue by gmnamra** [jvolkman/repairwheel#18]
It seems that clang is not supported. 
When I run this on wheel that was generated with clang and uses libc++.1.dylib that is not in the white list.

**Comment by jvolkman** [comment]
What happens that is unexpected? Can you provide a reproducer?

**Comment by gmnamra** [comment]
[reproducer_out.txt](https://github.com/jvolkman/repairwheel/files/13274472/reproducer_out.txt)
I can send you the wheel. When I used repairwheel, it complained about libgcc
But here is the output 

(arm_env_python311) sainzdem@sainzdem-933962 mac_mri % python mri_install_demo.py
Python Version: 3.11.5 (main, Sep 11 2023, 08:31:25) [Clang 14.0.6 ]
[reproducer_out.txt](https://github.com/jvolkman/repairwheel/files/13274464/reproducer_out.txt)

Traceback (most recent call last):
  File "/Users/sainzdem/Documents/DIVA/mac_mri/mri_install_demo.py", line 10, in <module>
    from MultiResImagePy import MultiResImage
ImportError: dlopen(/Users/sainzdem/opt/anaconda3/envs/arm_env_python311/lib/python3.11/site-packages/MultiResImagePy.cpython-311-darwin.so, 0x0002): Library not loaded: @rpath/libc++.1.dylib
  Referenced from: <45AAF4A4-076E-3FC6-848E-278334E55E20> /Users/sainzdem/opt/anaconda3/envs/arm_env_python311/lib/python3.11/site-packages/MultiResImagePy.cpython-311-darwin.so
  Reason: tried: '/Users/garakana/opt/anaconda3/envs/native/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/garakana/opt/anaconda3/envs/native/lib/libc++.1.dylib' (no such file), '/Users/sainzdem/opt/anaconda3/envs/arm_env_python311/lib/python3.11/site-packages/multiresimage/lib/libc++.1.dylib' (no such file), '/Users/garakana/opt/anaconda3/envs/native/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/garakana/opt/anaconda3/envs/native/lib/libc++.1.dylib' (no such file), '/Users/sainzdem/opt/anaconda3/envs/arm_env_python311/lib/python3.11/site-packages/multiresimage/lib/libc++.1.dylib' (no such file), '/Users/sainzdem/opt/anaconda3/envs/arm_env_python311/bin/../lib/libc++.1.dylib' (no such file), '/Users/sainzdem/opt/anaconda3/envs/arm_env_python311/bin/../lib/libc++.1.dylib' (no such file)

**Comment by jvolkman** [comment]
Seems this is due to the binaries being built for conda. Delocate (which repairwheel delegates to) will skip any libraries under  /System or /usr/lib, and a normal c++ binary will look for libc++ at `/usr/lib/libc++.1.dylib`.

Have you tried using [delocate](https://github.com/matthew-brett/delocate) directly? Do you get the same result?

**Comment by gmnamra** [comment]
The issue also stems from osx new caching of dylibs. So there is no libc++.1.dylib at /usr/lib. I think the other issue is on my side which is to link dylibs and not specific versions. 
Thanks

**Comment by jvolkman** [comment]
The file isn't there, but compiled binaries still reference that name. So I think delocate would still end up skipping it.

```shell
$ ls /usr/lib/libc++.1.dylib
ls: /usr/lib/libc++.1.dylib: No such file or directory
$ clang++ -o /tmp/test /tmp/test.cpp
$ otool -L /tmp/test
/tmp/test:
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
```

**Comment by jvolkman** [comment]
Feel free to reopen if you need more help.
