### ISSUE TITLE
repairwheel 0.2.8 generating invalid ELF libraries on aarch64

### ISSUE THREAD

**Issue by fidothe** [jvolkman/repairwheel#33]
Repairing an aarch64 linux wheel with an external .so dependency using repairwheel 0.2.8 is generating a bad ELF:

```
Python 3.12.2 (main, May 13 2024, 17:20:29) [GCC 12.2.1 20221121 (Red Hat 12.2.1-7)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from saxonche import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /.../lib/python3.12/site-packages/saxonche.cpython-312-aarch64-linux-gnu.so: ELF load command past end of file
```

If I set `LD_LIBRARY_PATH` and use the unrepaired wheel, there are no problems, so it's not a problem with the unrepaired `.so`, and repairing the wheel using a directly installed`auditwheel` 6.0.0 produces wheels that don't have this problem either.

**Comment by jvolkman** [comment]
Would you be able to share the input wheel by chance?

**Comment by fidothe** [comment]
Brilliant, thanks. I was hoping to have a wheel I could share, but that got delayed... However, I am about to build new wheels, so I will test this out ASAP...
